package com.example.ever_care.activities;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import com.example.ever_care.R;
import com.example.ever_care.models.HealthData;
import com.example.ever_care.utils.FirebaseDatabaseHelper;
import com.example.ever_care.utils.PreferenceManager;

import java.util.Date;

public class HealthDataActivity extends AppCompatActivity {

    private Toolbar toolbar;
    private EditText editTextTemperature, editTextBloodPressure, editTextSugarLevel;
    private Button buttonSaveHealthData;
    private ProgressBar progressBar;

    private PreferenceManager preferenceManager;
    private FirebaseDatabaseHelper databaseHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_health_data);

        preferenceManager = new PreferenceManager(getApplicationContext());
        databaseHelper = new FirebaseDatabaseHelper();

        // Initialize toolbar
        toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        // Initialize views
        editTextTemperature = findViewById(R.id.editTextTemperature);
        editTextBloodPressure = findViewById(R.id.editTextBloodPressure);
        editTextSugarLevel = findViewById(R.id.editTextSugarLevel);
        buttonSaveHealthData = findViewById(R.id.buttonSaveHealthData);
        progressBar = findViewById(R.id.progressBar);

        // Set click listeners
        buttonSaveHealthData.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (validateInputs()) {
                    saveHealthData();
                }
            }
        });
    }

    private boolean validateInputs() {
        if (TextUtils.isEmpty(editTextTemperature.getText().toString().trim())) {
            editTextTemperature.setError("Temperature is required");
            return false;
        }

        if (TextUtils.isEmpty(editTextBloodPressure.getText().toString().trim())) {
            editTextBloodPressure.setError("Blood pressure is required");
            return false;
        }

        if (TextUtils.isEmpty(editTextSugarLevel.getText().toString().trim())) {
            editTextSugarLevel.setError("Sugar level is required");
            return false;
        }

        return true;
    }

    private void saveHealthData() {
        progressBar.setVisibility(View.VISIBLE);
        buttonSaveHealthData.setEnabled(false);

        float temperature = Float.parseFloat(editTextTemperature.getText().toString().trim());
        String bloodPressure = editTextBloodPressure.getText().toString().trim();
        float sugarLevel = Float.parseFloat(editTextSugarLevel.getText().toString().trim());
        Date recordedDate = new Date();

        // Determine elderly ID
        String elderlyId;
        if (preferenceManager.isElderly()) {
            elderlyId = preferenceManager.getUserId();
        } else {
            elderlyId = preferenceManager.getLinkedUserId();
        }

        // Create health data object
        HealthData healthData = new HealthData(
                null, // ID will be generated by Firebase
                temperature,
                bloodPressure,
                sugarLevel,
                recordedDate,
                elderlyId
        );

        // Save to Firebase
        databaseHelper.saveHealthData(healthData, new FirebaseDatabaseHelper.DataCallback<Boolean>() {
            @Override
            public void onSuccess(Boolean result) {
                progressBar.setVisibility(View.GONE);
                buttonSaveHealthData.setEnabled(true);
                Toast.makeText(HealthDataActivity.this, "Health data saved", Toast.LENGTH_SHORT).show();
                finish();
            }

            @Override
            public void onError(String errorMessage) {
                progressBar.setVisibility(View.GONE);
                buttonSaveHealthData.setEnabled(true);
                Toast.makeText(HealthDataActivity.this, "Error: " + errorMessage, Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}